
name = "pixlized-website"
compatibility_date = "2024-01-01"

# Astro Cloudflare adapter entry point
main = "dist/server/entry.mjs"

[assets]
directory = "./dist/client"

[env.production]
name = "pixlized-website"

[env.development]
name = "pixlized-website-dev"

[[d1_databases]]
binding = "CF_D1_DB"
database_name = "pixlized-db"
database_id = "ca758b75-74e3-4f20-b799-f8d6ecf62a57"
